version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      HVS6a89eF5iFLx6bOv/pUWRGT3Zhf2OllHm3AObEqTLk8IlrveWxE1kk2CkBE0Q0xOnUIOL+1X01s4AEmP0leAeftR8N15KaqY2aECNjNq2KvZTZybgkkTqX4Nsv2hGoXAzuZhE09JzKr3niGpp5M0+fauXXOGtycObp41i4Ij1I80lNo+qreQ7jUyzVtBL0UdvGyPGLB6o6JfaHHHpEZHHMeNhuVZbeCUtGpltqvrNag+YxAyC8Um+n4mSIP+/JIkEePOagM1sGgQp8fezFV4wEUQ0Eb49gfYiTnZ9NEV+6jZ/gKpnKJMDZPjs7GHCaHmGGiQr/osAUgmChFdoyDPP35cOZy7HJhIe+QwSZGFdj4kHaz8MyznS51/M2MPO7IoZq7qXQk+eEplpqpaaF1/SzsjXisXGwbAa6daCRYnMPLtnIhIM6La/JzIi6JeDC/UmHDcUqDP2HkZktCJiKSLx+cZy21sYpNn8UAGvz/drqpRPuI6J95fD0H2MH/qnVv9lOU1XfvAB7k91zoWfmhuU98JsseJA1YQPoJNaiB3ArSOoYaAL2uf0lCOoxHYxYpX3Ej5WcB9Igr7QarQr7MOPI2yXugEwufKKM9COZUV+Hal+FX7hbw/wICxECj+UnJpYd7XuJ3GY41G5TLXxRlrxkxRHKNqK5v0Rt/zsrAI8=
