version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      EKOYVXVipq/hzWkK+I2PWm1XiW9lDtmjp1M28hvcZP1K6q+w17YDQfH8s6rf2wsbL5DLYYP32gKHrqP5h52bi6MkEU1G1OoBybOqKnrbPgIqX8pQNMShZSoCfX4rLFl2QwyFFNsWMYCbFsp7P9TlstgdutlE29xZa3vV3W/k3M727NJUcdn+ejHzVcqG1ETS9HESJS/tSTIdeHChnFa+3u8xga1bHuu9xMXNLEqB/F5c686uWToC+3VDMsxou93gm1/3Jiq7gSmn0YFmTf0XBbll/vit0M5uWQbcZ/QfpQSpqEgi1AU8bdNDHLw2/yVfFwX/lP+g+8D+ixmryrCgkcMRkUmaL8Z8UjWuFsO3VGBtTZI2XaRD12jR/2Kvpryg1i2MXGdT4BP7Fpfty77IhS2/AlD5JYWV/cIGqFQhXglxpQP+xYxa4gnbuf5+ilUAF7VewXJI0ge7xWtdVuVFnxsBXS6pLdS9ee1DjWAL852hCftEzFpXow1Ai0uadNXdESHOcAeF4woUoZh5ZEL23AqjiI+2XTDNhsguqTc6giFIShWjMGyGJouo0Rt+XG9O9aoycEvoxcW/xcvCa7z/KSEG/orRiWY3PvGqTzDBsCTUD6f+YuABmm9vXQ9VEh3mv3kkqFuCxOwyIjj9S0eSZ+7UMqqvVxiwk7scP5fWAbQ=
