sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '10'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/surge.bash)"
- eval "$(curl -s https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: mpzLU8a/pSSgIG9vYG6OdePrA3Fy9Jes6plwae2CLv0tQACRgF/YcwPnCkO5xZA75e5WHM5RJBqzp2NYuHNHQcCOWtWXj5m957C8+UlmYlMil4FtjMkx8QLLoRCeiaL9fJKn8/LQyQsZC7xVINauhqHbH6mw+4vNpFZV86dpVn7rmBZ7SSywpsPgHngFyQ63k+k/ggOMEpdKgkvP5xPiw1gqw7h8IP8pUbOBC+fQ4HnA8Mnf7iKO0cvhDU5NSaAXbM2Cw44CxfDV43mFroZAziSRw0WHF1y5DpSNFdf5evzqSpJzM40SKAjpqwYF4M0U+wWnJnAh8Kp8dx2VN+CpOKE+QiO0JdWiYt98m14RBLQ2TixIsvJ6eeYzGGZvccwzg2Xusor5qzPZwfcuYB3U86dhLgipLdcIP3VVnxoukStksumxFBZIL6zmXz4wUbGEpLNV20/gSBcmIeNWN/4mEpVhHmKWR/FkxN/ramhS+oIktyVsBggHsxUSWnlbMJ1FMzQZvQDj3z8GCwLVdLNwqubgr7m+Dc3cS0++OuP+XTudjTiW7s8tBJWSIxVRBl4bMIYJCHZrbMZxI0q/5ZZzBc62n7DVodbM89XpADm+lDh75fUhXy1LaiVL5chh/i8ks0JdhWXMyTGC9ornOQFyk1bXuOsnGf0Y29EHarmZJH8=
