version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      kVpnwkj0j+pEPqLVfO2ixESgYTJuI2yLXxbHpvEOidy7ti841Xh+T1DVCxf6FaTASi22zqwg/1Z3jZbWMVtm+5pOBq8BK/nbXe0+KTfYiDzugB46Iqo66ef5BjpvqpaOiT8CUurKIBDt5EDsr2WzFWiC7JkZWck0kx7oobp0CZ/HADXcN4KPkBNe1JSTDFPF8kVNagI0fRveJiDspdVKIiL/RY6569UvwaRe5EizmXvoLufnEjVL2rubP0/pQTjAUh7cjfQ/PcNwW0VXUamnWP6A3QTBGBQwZsmRuRHG93JFX2FIdZAV7JBSB0/zwLkW5RrRoesg3paRwXsxKe6m7dhRueLnum8LxOng8gBw8gmpXSLP37SMIzwDPBa3YtlLgAthFl0IeBp65J1sh3DomLYTPDUh56yrnksQdoQya9aJZEHCiuK12TfPQGN8AzkkdnaL+VaR/XNlq5vwAjh6rVb6XqaLt4h/pcaE9zHgwckF9/Z5CUxViEhduknb5Rld4SupSi/6iGMqlaBOa/7mtUZJoqLrYLvWCnRppPzlqgGRSRXhhlbGhVEPrkjtRdDq0q/hj++GiCqghdEFfJ+67ScNYuBaRf9n2bi3ersogHbU/F/FjJgegehlueJylPsr/XMwiOXGNffab0ChAF7vo06OhH9KUIih5820XqEPZdM=
