sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '10'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffacc146944edb58d02bbc565bf467099b18/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: O/WjKb9MhTWxEr8MAv85nfTIN4+AV2EoOuJoOwGJPP23z2HQ2HN8ab1ZywhDoIB5bssKfFMmwxgKtgJj6kJIfx4FZVtcLWb1ceAMDTnCsNn/WP6X0QtbDzf3p/Qnzn5wJRRVukn7AnJEcaXSgbNUZrzwZWIFEys5IiQ9cenQ1Ke8rlOZSZsNY9hDbQFMpJ88d17EmgArVLXl09uAjGMacl+UNChp/MUrZ5IkX4Mg8iiMTl8Asxn6LS2yl2VmTSZtRyun1abMehcLS/+2ubgaKN9hbt6+rleV6hziOIGo4RXCqgzZaBHGOPkYv+nfURuv/QqgYFcnHxQOGsGhU/hw1hlhgAfi3Npf9G68PZXVBOe4wH2+qC3Ir9CgqhO9BNTZBBIJaCEA7CxXTkaDJMZDGh+eT/2Q2PL18H59D1heZnBYZoQe57f5yzMIbKCms4jASN982XeNOZWSGjzST8p8rirh84M1hQGEXPzOXa2UOjzh4FzSxQrG/kNjepF2D2HaVoD5uQ+N0qIUrob5iDHVMVQBnkhTvnxYmUAUemOiZPR0OeiqveB5d5frxddz9K6Sv8QSx2nQ32983UNQ1V04BsH3SILaAyGBl1k23GtgOTQ5Vp8ZSn2biGVKbvIoZQzgS/h8IEhyIg3R3Ep/uxaIkcbegu57oEoy+XmTMxtILxA=
